### ISSUE TITLE
Reconnect does not work. When connection lost, it crash (CRITICAL)

### ISSUE THREAD

**Issue by mike-aungsan** [socketio/socket.io-redis#190]
It does not survive redis server disconnect / restart.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by mike-aungsan** [comment]
Providing pubClient and subClient fix.

const socketioRedisAdapter = socketioRedis({
  pubClient: redisPubClient,
  subClient: redisSubClient
})
