### ISSUE TITLE
args.shift is not a function

### ISSUE THREAD

**Issue by mike-aungsan** [socketio/socket.io-redis#191]
/home/ubuntu/node/node_modules/socket.io-redis/index.js:149
    if (uid == args.shift()) return debug('ignore same uid');
                    ^

TypeError: args.shift is not a function
    at Redis.onmessage (/home/ubuntu/node/node_modules/socket.io-redis/index.js:149:21)
    at emitTwo (events.js:106:13)
    at RedisClient.emit (events.js:191:7)
    at return_pub_sub (/home/ubuntu/node/node_modules/redis/index.js:783:18)
    at RedisClient.return_reply (/home/ubuntu/node/node_modules/redis/index.js:828:9)
    at JavascriptRedisParser.returnReply (/home/ubuntu/node/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/ubuntu/node/node_modules/redis-parser/lib/parser.js:560:12)
    at Socket.<anonymous> (/home/ubuntu/node/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
Program node . exited with code 1

**Comment by darrachequesne** [comment]
Could you provide some context please?
