### ISSUE TITLE
Error: NOAUTH Authentication required with previous established redis connection

### ISSUE THREAD

**Issue by moxious** [socketio/socket.io-redis#206]
We've been seeing somewhat random errors that bubble up like this in logs.

Redis googling says that on connect, redis is expecting a password to be sent.  Trouble with that is that the redis instance in question isn't configured to require auth, and has been running successfully with the same code hitting it for several months now.

```
Error: NOAUTH Authentication required.
 at JavascriptReplyParser._parseResult (/src/node_modules/socket.io-redis/node_modules/redis/lib/parsers/javascript.js:43:16)
 at JavascriptReplyParser.try_parsing (/src/node_modules/socket.io-redis/node_modules/redis/lib/parsers/javascript.js:114:21)
 at JavascriptReplyParser.run (/src/node_modules/socket.io-redis/node_modules/redis/lib/parsers/javascript.js:126:22)
 at JavascriptReplyParser.execute (/src/node_modules/socket.io-redis/node_modules/redis/lib/parsers/javascript.js:107:10)
 at Socket.<anonymous> (/src/node_modules/socket.io-redis/node_modules/redis/index.js:131:27)
 at emitOne (events.js:90:13)
 at Socket.emit (events.js:182:7)
 at readableAddChunk (_stream_readable.js:153:18)
 at Socket.Readable.push (_stream_readable.js:111:10)
 at TCP.onread (net.js:534:20)
```

We're using socket.io-redis 1.1.1, which I'm now seeing is substantially behind, but wondering if anyone has seen this or has potential suggestions.

The way we use the module is like this:

```
import socketIo from 'socket.io';
import ioRedis from 'socket.io-redis';

// (...) 

  const io = socketIo(server);

  io.adapter(ioRedis({
    host: config.getConfig().redis.host,
    port: config.getConfig().redis.port,
    key: config.getConfig().notification.key,
  }));
```

**Comment by svarughese91** [comment]
Does anyone know how to solve this I am seeing this error as well

**Comment by darrachequesne** [comment]
@moxious that's weird, could you please check whether that's a known issue in the redis client? There are several mention of `NOAUTH Authentication required` in their issue tracker: https://github.com/NodeRedis/node_redis/search?q=NOAUTH+Authentication+required&type=Issues&utf8=%E2%9C%93

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by nicholaswmin** [comment]
Use the full URI instead of passing a connections object like so:

```js
io.adapter(redis('redis://user:password@host:29599'))
```
