### ISSUE TITLE
Identifier 'sendAck' has already been declared

### ISSUE THREAD

**Issue by Nerfair** [socketio/socket.io-redis#216]
This partly duplicates this issue https://github.com/socketio/socket.io-redis/issues/211, but last one was closed to soon because of lack of information provided.

Problem is

```
  /home/htdocs/socket/server/node_modules/socket.io-redis/index.js:258
          }
          ^
  SyntaxError: Identifier 'sendAck' has already been declared
      at Object.exports.runInThisContext (vm.js:76:16)
      at Module._compile (module.js:542:28)
      at Object.Module._extensions..js (module.js:579:10)
      at Module.load (module.js:487:32)
      at tryModuleLoad (module.js:446:12)
      at Function.Module._load (module.js:438:3)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/home/htdocs/socket/server/server.js:47:5)
      at Module._compile (module.js:570:32)
      at Object.Module._extensions..js (module.js:579:10)
```

server.js code

```
const port = 3001 + (parseInt(process.env.NODE_APP_INSTANCE) || 0); // 3001, 3002, 3003 ...

const io = require('socket.io')(port);

io.adapter(
    require('socket.io-redis')({
        host: 'localhost',
        port: 6379
    })
);

io.on('connection', function (socket) {
    console.log('connected');
});
```

Package.json is

```
{
  "name": "test",
  "version": "0.0.0",
  "description": "",
  "dependencies": {
    "file-type": "latest",
    "htmlspecialchars": "latest",
    "jsonwebtoken": "latest",
    "mysql": "latest",
    "pmx": "latest",
    "redis": "latest",
    "socket.io": "1.7.4",
    "socket.io-redis": "latest",
    "twemoji": "latest"
  },
  "author": "",
  "license": "UNLICENSED",
  "private": true
}
```

_Socket.io is 1.7.4 version because off https://github.com/socketio/socket.io-redis/issues/214_

How to reproduce: **run socket.io server as cluster**, there is no error if you run single instance of socket.io, but if you run several of them, server crashes. 

Latest version of socket.io-redis is a must, because error happens only with version 3 >=, version 2.0.1 works fine and as a separate instance, and as cluster

Possible fix: rewrite `sendAck` ([index.js#L236](https://github.com/socketio/socket.io-redis/blob/master/index.js#L236)  and [index.js#L252](https://github.com/socketio/socket.io-redis/blob/master/index.js#L252)) methods to anonymous one

```
      case requestTypes.remoteJoin:

        var socket = this.nsp.connected[request.sid];
        if (!socket) { return; }

        socket.join(request.room, function(){
            var response = JSON.stringify({
                requestid: request.requestid
            });

            pub.publish(self.responseChannel, response);
        });
        break;

      case requestTypes.remoteLeave:

        var socket = this.nsp.connected[request.sid];
        if (!socket) { return; }

        socket.leave(request.room, function(){
            var response = JSON.stringify({
                requestid: request.requestid
            });

            pub.publish(self.responseChannel, response);
        });
        break;
```
this solution is working perfectly for a week on production chat application.

**Comment by darrachequesne** [comment]
Closed by #213
