### ISSUE TITLE
Socket.IO Redis crash from notepack.io encoding exception

### ISSUE THREAD

**Issue by beaucollins** [socketio/socket.io-redis#228]
Socket.IO 5.1.0 caused crash on our server. It looks like its due to an exception in the new notepack.io dependency.

```
Error: Number is not finite
    at _encode (./node_modules/notepack.io/lib/encode.js:93:13)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
    at _encode (./node_modules/notepack.io/lib/encode.js:286:15)
```

**Comment by artofspeed** [comment]
@darrachequesne should we put try catch around `msgpack.encode()` and `msgpack.decode` functions?

**Comment by beaucollins** [comment]
@artofspeed it comes down to number types that fail `isFinite`. So `NaN`, `Infinity` and `-Infinity`. `msgpack-lite` supports those values.

For now I forked `socket.io-redis` to allow custom encoder/decoder functions and wrapped `notepack.io` to use `msgpack-lite` when it throws an error during encode/decode.

**Comment by beaucollins** [comment]
I have a PR darrachequesne/notepack#3 to discuss the best way to resolve the problem.

**Comment by darrachequesne** [comment]
Closed by https://github.com/darrachequesne/notepack/pull/4.
