### ISSUE TITLE
ioredis and dropBufferSupport

### ISSUE THREAD

**Issue by emhagman** [socketio/socket.io-redis#233]
Using versions:
```
"socket.io": "^2.0.3",
"socket.io-emitter": "^3.0.1"
"socket.io-redis": "^5.1.0"
```

Hi!

Thanks for writing this amazing library :) I have a question.

It was my understanding that the newer versions no longer need to use `return_buffer: true` in the client configuration? This seems to work for node_redis but if using ioredis like in the example docs,
I get the following:

Only when I instantiate the client like so does it work:
```
const redisPub = new Redis(Config.socketRedis.rawUrl, {
    dropBufferSupport:      false,
    showFriendlyErrorStack: Config.env !== 'production'
});
const redisSub = new Redis(Config.socketRedis.rawUrl, {
    dropBufferSupport:      false,
    showFriendlyErrorStack: Config.env !== 'production'
});
```

It only works with `dropBufferSupport: false`.
The `socket.io-redis` call looks like this:
```
const adapter = require('socket.io-redis');
io.adapter(adapter({ pubClient: redisPub, subClient: redisSub }));
```

With `dropBufferSupport: true`, I get the following after calling `io.emit`:
```
/usr/src/app/node_modules/socket.io-redis/node_modules/notepack.io/lib/decode.js:239
   throw new Error('Could not parse');
   ^

 Error: Could not parse
     at Decoder.parse (/usr/src/app/node_modules/socket.io-redis/node_modules/notepack.io/lib/decode.js:239:9)
     at Object.decode (/usr/src/app/node_modules/socket.io-redis/node_modules/notepack.io/lib/decode.js:244:23)
     at Redis.onmessage (/usr/src/app/node_modules/socket.io-redis/index.js:148:24)
     at emitThree (events.js:116:13)
     at Redis.emit (events.js:197:7)
     at Redis.exports.returnReply (/usr/src/app/node_modules/ioredis/lib/redis/parser.js:119:14)
     at JavascriptRedisParser.returnReply (/usr/src/app/node_modules/ioredis/lib/redis/parser.js:27:13)
     at JavascriptRedisParser.execute (/usr/src/app/node_modules/redis-parser/lib/parser.js:574:12)
     at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:191:7)
     at readableAddChunk (_stream_readable.js:178:18)
     at Socket.Readable.push (_stream_readable.js:136:10)
     at TCP.onread (net.js:561:20)
```

**Comment by darrachequesne** [comment]
It seems `socket.io-redis` only works with `dropBufferSupport: false`, as you noted, since the packets are encoded/decoded as buffers with msgpack. It may be worth a note in the Readme!

Reference: https://github.com/luin/ioredis/wiki/Improve-Performance#dropbuffersupport-option
