### ISSUE TITLE
Uncaught Exception thrown even after including error handler on connection lost

### ISSUE THREAD

**Issue by prerak1992** [socketio/socket.io-redis#236]
Sample code
````
var io = require('socket.io').listen(server);
var redisAdapter = require('socket.io-redis');
var pub = redis(port,host, { auth_pass: password });
var sub = redis(port,host, { auth_pass: password });
var _a = redisAdapter({ pubClient: pub, subClient: sub })
io.adapter(_a);
io.of('/').adapter.on('error', function(){ // Handler 1
   console.log('1')
});
_a.pubClient.on('error', function(){ // Handler 2
   console.log('2')
});
_a.subClient.on('error', function(){ // Handler 3
   console.log('3')
});
````
Disconnect internet

````
 events.js:160
       throw er; // Unhandled 'error' event
       ^
 Error: Redis connection to redis-xxxxx.c9.us-east-1-2.ec2.cloud.redislabs.com:xxxxx failed - read ECONNRESET
     at exports._errnoException (util.js:1018:11)
     at TCP.onread (net.js:568:26)
````
Some redis errors are thrown, when the internet connection goes down. Few are caught by handler (2) and (3), but a few are uncaught exception and kill the process. As per documentation these should also be caught by either of the handlers (Probably handler 1).

**Comment by prerak1992** [comment]
I just found that my socket.io and socket.io-redis release versions were outdated. When I upgraded the versions, the uncaught exceptions per caught by handler 1.

Thus closing the issue.
