### ISSUE TITLE
Adapter with emitter issue

### ISSUE THREAD

**Issue by CrackerakiUA** [socketio/socket.io-redis#252]
I get below error when i try to do emit. I am connecting with same redit on which i am attaching adapter.
```C:\Work\node_modules\socket.io-redis\node_modules\socket.io-adapter\index.js:136
this.encoder.encode(packet, function(encodedPackets) {
^

TypeError: Cannot read property 'encode' of undefined
at Redis.Adapter.broadcast (C:\Work\node_modules\socket.io-redis\node_modules\socket.io-adapter\index.js:136:15)
at Redis.broadcast (C:\Work\node_modules\socket.io-redis\index.js:416:33)
at Redis.onmessage (C:\Work\node_modules\socket.io-redis\index.js:165:20)
at emitThree (events.js:116:13)
at RedisClient.emit (events.js:194:7)
at return_pub_sub (C:\Work\node_modules\redis\index.js:796:18)
at RedisClient.return_reply (C:\Work\node_modules\redis\index.js:833:9)
at JavascriptRedisParser.returnReply (C:\Work\node_modules\redis\index.js:192:18)
at JavascriptRedisParser.execute (C:\Work\node_modules\redis-parser\lib\parser.js:574:12)
at Socket. (C:\Work\node_modules\redis\index.js:274:27)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:547:20)```

**Comment by CrackerakiUA** [comment]
My code is below
```var io = require('socket.io')(this, { origins: ':'});
var rhost = 'xxx.xx.xx.xxx';
var rport = xxxx;
var Redis = require("ioredis");
sd._emiter = require('socket.io-emitter')(new Redis(rport, rhost));
io.adapter(require('socket.io-redis')({ host: rhost, port: rport }));
sd._emiter.emit('test', 'qeweqwewqe');```

**Comment by darrachequesne** [comment]
It sounds like a version problem, please see https://github.com/socketio/socket.io-redis/releases/tag/5.0.0.
