### ISSUE TITLE
TypeError: this.adapter.addAll is not a function

### ISSUE THREAD

**Issue by xzk821649509** [socketio/socket.io-redis#271]
my project use `socket.io` 2.0.4   `socket.io-redis `5.2.0 

```
const httpServer = require('http').createServer(app);
const io = require('socket.io')(httpServer);
const ioc = require('socket.io-redis');
io.adapter(ioc({ host: socketRedisConfig.host, port: socketRedisConfig.port, password: socketRedisConfig.password}));
```

getting error
```
0|server   | TypeError: this.adapter.addAll is not a function
0|server   |     at Socket.join (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:244:16)
0|server   |     at Socket.onconnect (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:299:8)
0|server   |     at /home/htdocs/socket/server/node_modules/socket.io/lib/namespace.js:171:16
0|server   |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|server   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by shlomisas** [comment]
@xzk821649509 , what was the solution here?

**Comment by darrachequesne** [comment]
Both `socket.io@2.0.4` and `socket.io-redis@5.2.0` include `socket.io-adapter@~1.1.0`, which adds the `addAll` method (https://github.com/socketio/socket.io-adapter/commit/f627cd2db1eb2f18aef82ac991ddf8ea799b662d).

I'd say there's an earlier version of `socket.io-adapter` in your dependency tree. Could you please check if reinstalling from scratch solves the issue? Thanks!
