### ISSUE TITLE
clients.length cast 0 when I use adapter.remoteJoin up to 6500 clients

### ISSUE THREAD

**Issue by NaughtyDogOfSchrodinger** [socketio/socket.io-redis#303]
[2019-04-16 16:55:20.112] [INFO] console - schedule:Tue Apr 16 2019 16:55:20 GMT+0800 (GMT+08:00)
[2019-04-16 16:55:20.335] [INFO] console - Error: timeout reached while waiting for clients response
    at Timeout._onTimeout (/var/classroom/node/jianghu/node_modules/socket.io-redis/index.js:457:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2019-04-16 16:55:20.335] [INFO] console - 6046
[2019-04-16 16:55:25.095] [INFO] console - schedule:Tue Apr 16 2019 16:55:25 GMT+0800 (GMT+08:00)
[2019-04-16 16:55:26.472] [INFO] console - Error: timeout reached while waiting for clients response
    at Timeout._onTimeout (/var/classroom/node/jianghu/node_modules/socket.io-redis/index.js:457:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2019-04-16 16:55:26.472] [INFO] console - 6519
[2019-04-16 16:55:30.580] [INFO] console - schedule:Tue Apr 16 2019 16:55:30 GMT+0800 (GMT+08:00)
[2019-04-16 16:55:33.758] [INFO] console - Error: timeout reached while waiting for clients response
    at Timeout._onTimeout (/var/classroom/node/jianghu/node_modules/socket.io-redis/index.js:457:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2019-04-16 16:55:33.759] [INFO] console - 0
[2019-04-16 16:55:36.440] [INFO] console - schedule:Tue Apr 16 2019 16:55:36 GMT+0800 (GMT+08:00)

**Comment by knoxcard2** [comment]
Please post your websocket redis code...

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
