### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by joaoritter** [socketio/socket.io-redis#305]
Connection via node js. Running using Pm2 clustering. There are two instances running and socket.io-redis is in place to manage socket sessions between them.

Connecting like:
`
io.adapter(redis({ host: 'localhost', port: REDIS_PORT }));
`

and the error is thrown when I eventually call:

`
io.to(<room_name>).emit(<event>)
`

`
TypeError: Cannot read property 'apply' of undefined
    at Command.patchedEnd (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/census/plugins/redis.js:104:34)
    at Command.contextWrapper [as callback] (/usr/local/lib/node_modules/pm2/node_modules/@opencensus/core/build/src/internal/cls-ah.js:66:28)
    at normal_reply (/home/joao_roof_io/api/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/joao_roof_io/api/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/home/joao_roof_io/api/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/joao_roof_io/api/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/joao_roof_io/api/node_modules/redis/index.js:274:27)
    at Socket.contextWrapper (/usr/local/lib/node_modules/pm2/node_modules/@opencensus/core/build/src/internal/cls-ah.js:66:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
`

![image](https://user-images.githubusercontent.com/5597861/57176566-4f448980-6e0e-11e9-9300-e5647606dfc3.png)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
