### ISSUE TITLE
Error: Redis connection to 6379:6379 failed - connect EINVAL 0.0.24.235:6379 - Local (0.0.0.0:0)

### ISSUE THREAD

**Issue by mandaputtra** [socketio/socket.io-redis#309]
Hi I cant connect to redis, with this adapter? do you had any solution? never had EINVAL message before. My Code :

```
// this file will contains websockets controllers
const socketio = require('socket.io')
const redisAdapter = require('socket.io-redis')

const users = {}

module.exports = function ws(server) {
  const io = socketio.listen(server)
  // redis adapter
  io.adapter(
    redisAdapter({
      host: process.env.REDIS_HOST || '127.0.0.1',
      port: process.env.REDIS_PORT || 6379
    })
  )

  // websockets controllers
  io.on('connection', function(socket) {
    // get unique ID and unique rooms
    socket.on('grantId', id => {
      socket.nickname = id
      users[id] = socket.id
    })

    // send message
    socket.on('chat', msg => {
      const { reciever, message } = msg
      socket.broadcast.to(users[reciever]).emit('chat', message)
    })

    // Client disconnected
    socket.on('disconnect', () => {
      delete users[socket.nickname]
    })
  })

  return io
}

```

Full error message :

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 6379:6379 failed - connect EINVAL 0.0.24.235:6379 - Local (0.0.0.0:0)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:59:10)
Emitted 'error' event at:
    at RedisClient.onError (/home/maxsol/Works/yanmar-nodejs/node_modules/socket.io-redis/index.js:118:12)
    at RedisClient.emit (events.js:198:13)
    at RedisClient.on_error (/home/maxsol/Works/yanmar-nodejs/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/home/maxsol/Works/yanmar-nodejs/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by fabiencoppenspdgc** [comment]
@mandaputtra We are seeing the same issue. Our Redis is running as an AWS Elasticache managed Redis. How did you solve this?

**Comment by sjaswinder82** [comment]
> @mandaputtra We are seeing the same issue. Our Redis is running as an AWS Elasticache managed Redis. How did you solve this?

Did you got solution for this ?
