### ISSUE TITLE
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.

### ISSUE THREAD

**Issue by Nandhan-augment** [socketio/socket.io-redis#336]
I'm getting this error, 
Version ==>  "socket.io-redis": "^5.2.0",
Can anybody tell why this error occurs?

events.js:174
      throw er; // Unhandled 'error' event
      ^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (node_modules/redis/index.js:664:14)
    at Socket.<anonymous> (node_modules/redis/index.js:293:14)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by bsjaffer** [comment]
I am also facing same issue. any solution for this ?

**Comment by iyjian** [comment]
@bsjaffer 

fyi:  https://github.com/socketio/socket.io-redis/issues/236

**Comment by darrachequesne** [comment]
This error means that you somehow lost connection with the Redis server.

This might be normal (Redis maintenance, network error, ...) and the Redis client should reconnect properly after a given delay.

You can catch the error with:

```js
io.of('/').adapter.on('error', (err) => {
  // ...
});
```
