### ISSUE TITLE
TypeError: this.adapter.add is not a function

### ISSUE THREAD

**Issue by user09876090** [socketio/socket.io-redis#390]
I'm using socket.io "^1.7.1", and "socket.io-redis": "^6.0.1" when I am doing the following
```
var io = require('socket.io')(server, {
	pingTimeout: 60000,
	cookie: false,
	handlePreflightRequest: (req, res) => {
		res.writeHead(200, {
			'Access-Control-Allow-Origin': '*',
			'Access-Control-Allow-Methods': 'GET,POST',
			'Access-Control-Allow-Headers': ['authorization', 'sessionId'],
			'Access-Control-Allow-Credentials': true,
		})
		res.end()
	},
})
const redisAdapter = require('socket.io-redis')

io.adapter(redisAdapter({ host: config.server, port: config.port }))
```
then I am getting this error
```
 this.adapter.add(this.id, room, function(err){
               ^

TypeError: this.adapter.add is not a function
    at Socket.join (/Users/Desktop/project/node_modules/socket.io/lib/socket.js:242:16)
    at Socket.onconnect (/Users/Desktop/project/node_modules/socket.io/lib/socket.js:295:8)
    at /Users/Desktop/project/node_modules/socket.io/lib/namespace.js:172:16
```
Any idea what's not write in my code?

**Comment by user09876090** [comment]
@darrachequesne

**Comment by user09876090** [comment]
So, I was doing some reading and it turned out that my socket.io-redis version was not compatible with socket.io. I have updated my socket.io version to 2.4.1 and not this issue is resovled
