### ISSUE TITLE
Unpack error

### ISSUE THREAD

**Issue by rafael-custodio** [socketio/socket.io-redis#40]
I'm using redis as adapter and sometimes it gives me the error

```
TypeError: Object #<Object> has no method 'readUInt64BE'
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:131:18)
    at Decoder.map (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:34:23)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:68:17)
    at Decoder.map (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:34:23)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:68:17)
    at Decoder.map (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:34:23)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:68:17)
    at Decoder.array (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:51:21)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:74:17)
    at Decoder.map (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:34:23)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:68:17)
    at Decoder.array (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:51:21)
    at Decoder.parse (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:74:17)
    at Object.decode (/var/www/00k-admin/node/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:199:23)
    at Redis.onmessage (/var/www/00k-admin/node/node_modules/socket.io-redis/index.js:93:24)
    at RedisClient.EventEmitter.emit (events.js:106:17)
```

**Comment by didaxRedux** [comment]
This error is caused by the msgpack module loaded by the socket.io-redis.
I've suggested a corretion... see my pull requests https://github.com/socketio/socket.io-redis/pull/105
