### ISSUE TITLE
Error launching package in Node

### ISSUE THREAD

**Issue by joswhite** [socketio/socket.io-redis#63]
<p>I have version 0.12.2 of Node, and I'm not able to get socket.io-redis to launch. I just get this error:</p>
<pre><code>Express server listening on port 3000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (C:\Users\JWhite\Downloads\socket.io-redis-sample\node_modules\socket.io-redis\node_modules\redis\index.js:185:24)
    at Socket.<anonymous> (C:\Users\JWhite\Downloads\socket.io-redis-sample\node_modules\socket.io-redis\node_modules\redis\index.js:95:14)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)</code></pre>
<p>Any suggestions? Is it possible this package needs to be updated to be compatible with Node 0.12? You can replicate my issue by downloading the package <code>socket.io-redis-sample</code> from Github using version 12.2 of Node and then running <code>npm install</code> and <code>npm start</code> in the base directory. Thanks!

**Comment by belbis** [comment]
redis server is not started that's why there is the ECONNREFUSED error. 
run `redis-server &` (or however you start it up) before trying `npm start`

**Comment by joswhite** [comment]
Ok, thanks! That helps a lot, I guess I just had no clue how to start it up!
